<!-- GitHub Star -->
<a class="github-button" href="https://github.com/hexojs/hexo" data-count-href="/hexojs/hexo/stargazers" data-count-api="/repos/hexojs/hexo#stargazers_count" data-count-aria-label="# stargazers on GitHub" aria-label="Star hexojs/hexo on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/hexojs/hexo/fork" data-count-href="/hexojs/hexo/network" data-count-api="/repos/hexojs/hexo#forks_count" data-count-aria-label="# forks on GitHub" aria-label="Fork hexojs/hexo on GitHub">Fork</a>
<!-- Tweet button -->
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://hexo.io/" data-text="Hexo - A fast, simple &amp; powerful blog framework powered by Node.js." data-hashtags="hexo,nodejs">Tweet</a>
<!-- Twitter follow button -->
<a href="https://twitter.com/hexojs" class="twitter-follow-button" data-show-count="false">Follow @hexojs</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script>
