import {
  IconBrowserElectronLight,
  IconBrowserChrome,
  IconBrowserChromeBeta,
  IconBrowserChromeCanary,
  IconBrowserChromeForTesting,
  IconBrowserMozillaFirefox,
  IconBrowserEdge,
  IconBrowserChromium,
  IconBrowserFirefoxNightly,
  IconBrowserFirefoxDev,
  IconBrowserEdgeCanary,
  IconBrowserEdgeBeta,
  IconBrowserEdgeDev,
  IconBrowserWebkit,
  IconGeneralGlobe,
} from '@cypress-design/vue-icon'

export const allBrowsersIcons = {
  'electron': IconBrowserElectronLight,
  'chrome': IconBrowserChrome,
  'chrome beta': IconBrowserChromeBeta,
  'canary': IconBrowserChromeCanary,
  'chrome canary': IconBrowserChromeCanary,
  'chrome for testing': IconBrowserChromeForTesting,
  'custom chrome for testing': IconBrowserChromeForTesting,
  'chromium': IconBrowserChromium,
  'custom chromium': IconBrowserChromium,
  'firefox': IconBrowserMozillaFirefox,
  'firefox nightly': IconBrowserFirefoxNightly,
  'firefox developer edition': IconBrowserFirefoxDev,
  'edge': IconBrowserEdge,
  'edge beta': IconBrowserEdgeBeta,
  'edge canary': IconBrowserEdgeCanary,
  'edge dev': IconBrowserEdgeDev,
  'webkit': IconBrowserWebkit,
  'generic': IconGeneralGlobe,
}
