import Button from './Button'
import { mount } from '@cypress/evergreen/dist/main.bundle'
import docs from '../../tests/plugins/docs'
import vueLiveExample from '../../tests/plugins/vueLive'

async function retry(fn, n = 0) {
  try {
    await fn()
  } catch (err) {
    if (n > 20) throw err
    await new Promise((resolve) => setTimeout(resolve, 10))
    return retry(fn, n + 1)
  }
}
const getElementByTestId = id => document.querySelectorAll(`[data-testid=${id}`)[0]

docs(Button)

// I wish this could be generated by the mount command :-)
vueLiveExample(
  `<Button
  :helloText="'Heyo'"
  :goodbyeText="'bye yall'"
 />`, { components: { Button } })


describe('Button', () => {
  it('works', async () => {
    const wrapper = mount(Button)

    expect(wrapper.exists()).to.be.ok

    // This fails... because of some owner document issue?
    // await mouse.click(
    //   $cyDom.getElementCoordinatesByPosition($(wrapper.vm.$el))
    //     .fromElViewport
    // )

    await wrapper.trigger('click')

    await retry(() => expect(getElementByTestId('byeButton').innerText).to.contain('Goodbye'))
  })
})


