export type Styles = {
  accent00: string;
  accent01: string;
  accent02: string;
  brand00: string;
  brand01: string;
  chill05: string;
  chill10: string;
  chill20: string;
  chill30: string;
  chill40: string;
  chill50: string;
  chill60: string;
  chill70: string;
  chill80: string;
  chill90: string;
  cran50: string;
  green05: string;
  green10: string;
  green20: string;
  green30: string;
  green40: string;
  green50: string;
  green60: string;
  metal00: string;
  metal05: string;
  metal10: string;
  metal100: string;
  metal20: string;
  metal30: string;
  metal40: string;
  metal50: string;
  metal60: string;
  metal70: string;
  metal80: string;
  metal90: string;
  olive05: string;
  olive10: string;
  olive20: string;
  olive30: string;
  olive40: string;
  olive50: string;
  olive60: string;
  papaya05: string;
  papaya10: string;
  papaya20: string;
  papaya30: string;
  papaya40: string;
  papaya50: string;
  papaya60: string;
  red40: string;
  red50: string;
  red60: string;
  red70: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
