// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'a': string;
  'isClosed': string;
  'isSelected': string;
  'li': string;
  'nav': string;
  'searchInput': string;
  'ul': string;
}
export const cssExports: CssExports;
export default cssExports;
