import getenv from 'getenv'

// Where to fetch the remote "federated" schema TODO: add w/ stitching PR
// export const CYPRESS_INTERNAL_CLOUD_ENV = 'production'

export const CYPRESS_INTERNAL_DEBUG_PORT_STARTUP = getenv.int('CYPRESS_INTERNAL_DEBUG_PORT_STARTUP', 7200)

export const CYPRESS_INTERNAL_DEBUG_PORT_ELECTRON = getenv.int('CYPRESS_INTERNAL_DEBUG_PORT_ELECTRON', 7201)

export const CYPRESS_INTERNAL_DEBUG_PORT_CODEGEN = getenv.int('CYPRESS_INTERNAL_DEBUG_PORT_CODEGEN', 7202)

export const CYPRESS_INTERNAL_E2E_TESTING_SELF = getenv.bool('CYPRESS_INTERNAL_E2E_TESTING_SELF', false)

export const CYPRESS_INTERNAL_GQL_PORT = getenv.int('CYPRESS_INTERNAL_GQL_PORT', 52159)

export const CYPRESS_INTERNAL_GQL_TEST_PORT = getenv.int('CYPRESS_INTERNAL_GQL_TEST_PORT', 52100)
