version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@1.0.0


jobs:
  verify-ci-should-run:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Verify CI should run
          command: |
            # run CI when manually triggers via CircleCi Dashboard
            if [ <<pipeline.trigger_source>> == 'api' ]; then
              echo "Always run CI when manually triggered from the UI."
              exit 0
            fi

            if [[ <<pipeline.git.branch>> == "develop" || <<pipeline.git.branch>> == "release/"* ]]; then
              echo "Always run CI for develop and for release candidate branches."
              exit 0
            fi

            LAST_COMMIT_MESSAGE=<<pipeline.trigger_parameters.github_app.commit_message>>

            if [[ "$LAST_COMMIT_MESSAGE" =~ "run ci" ]]; then
              echo "Always run CI when the commit message includes 'run ci'."
              exit 0
            fi

            cancel_build () {
              echo "Canceling the CI build..."
              circleci-agent step halt
            }

            TRIGGER_INSTRUCTIONS="to trigger CI , include 'run ci' in the commit message or click the 'Trigger Pipeline' button in the CircleCI UI."

            if [ ! -z "${CIRCLE_PULL_REQUEST##*/}" ]; then
              DRAFT=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PULL_REQUEST##*/}" | jq '.draft')

              if [[ "${DRAFT}" == true ]]; then
                echo "Skipping CI; PR is in draft - $TRIGGER_INSTRUCTIONS"
                cancel_build
              fi

              echo "Always run CI for PR that is ready for review."
              exit 0
            fi

            echo "Skipping CI; branch in progress - $TRIGGER_INSTRUCTIONS"
            cancel_build
      - continuation/continue:
          configuration_path: .circleci/workflows.yml

workflows:
  # the setup-workflow workflow is always triggered.
  setup-workflow:
    jobs:
      - verify-ci-should-run
