name: "🐛 Bug report"
description: Report a bug found while using Cypress.
body:
  - type: markdown
    attributes:
      value: |
        Have a question? 👉 [Start a new discussion](https://github.com/cypress-io/cypress/discussions) or [ask in chat](https://on.cypress.io/discord).
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: Please provide a description including screenshots, stack traces, etc. [Troubleshooting tips](https://on.cypress.io/troubleshooting).
      placeholder: Currently...
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired behavior
      description: Remember, we're not familiar with the app you're testing, so please provide a clear description of what should happen.
      placeholder: In this situation, Cypress should...
  - type: textarea
    id: reproduction
    attributes:
      label: Test code to reproduce
      description: Please provide a failing test or repo we can run. You can fork [this repo](https://github.com/cypress-io/cypress-test-tiny), set up a failing test, then link to your fork. If you have never done this before, watch [this video](https://youtu.be/NnriKHmj5T8) for example.
      placeholder: Here is my failing test code and the app code to run the tests on...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Cypress Version
      description: What version of Cypress are you running? Run `cypress version` to see your current version. If possible, please update Cypress to the latest version first.
      placeholder: ex. 10.3.1
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node version
      description: What version of node.js are you using to run Cypress?
      placeholder: ex. v16.16.0
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system is Cypress running on when you are encountering your problem?  The more specific the better.  ie macOS 12.4 or Windows 10.0.19044.1889
      placeholder: ex. macOS 12.4
    validations:
      required: true
  - type: textarea
    id: debug-logs
    attributes:
      label: Debug Logs
      description: Please run Cypress in [debug mode](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) and print the entire set of logs here.  This will often make it easier for Cypress developers to help in debugging your problem.
      placeholder: Debug logging output
      render: shell
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Other
      placeholder: Any other details?
