name: "⬇️ Issue during install"
description: Report an issue while downloading Cypress.
labels: ['topic: installation']
body:
  - type: markdown
    attributes:
      value: |
        Have a question? 👉 [Start a new discussion](https://github.com/cypress-io/cypress/discussions) or [ask in chat](https://on.cypress.io/discord).

        If you're behind a corporate proxy, make sure to [configure it properly](https://on.cypress.io/proxy-configuration) before install.
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: Please provide a description including screenshots, stack traces, DEBUG logs, etc. [Troubleshooting tips](https://on.cypress.io/troubleshooting)
      placeholder: When I try to download Cypress...
    validations:
      required: true
  - type: textarea
    id: debug-logs
    attributes:
      label: Debug logs
      description: Include DEBUG logs setting [`DEBUG=cypress:*`](https://on.cypress.io/troubleshooting#Print-DEBUG-logs/). Include npm/yarn logs if applicable.
      placeholder: Debug logs
      render: Text
  - type: input
    id: version
    attributes:
      label: Cypress Version
      description: What version of Cypress are you trying to install?
      placeholder: ex. 10.3.1
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node version
      description: What version of node.js are you using to run Cypress?
      placeholder: ex. v16.16.0
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      options:
        - npm
        - yarn
        - Direct download
        - pnpm
        - other
    validations:
      required: true
  - type: input
    id: package-manager-version
    attributes:
      label: Package Manager Version
      description: What is the version of your chosen package manager?
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      options:
        - Linux
        - Mac
        - Windows
        - other
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: What is the version of the operating system you are running Cypress on?
      placeholder: ex 12.4
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other
      placeholder: Any other details?