name: "⬇️ Issue during install"
description: Report an issue while downloading Cypress.
labels: ['topic: installation']
body:
  - type: markdown
    attributes:
      value: |
        Have a question? 👉 [Start a new discussion](https://github.com/cypress-io/cypress/discussions) or [ask in chat](https://on.cypress.io/discord).

        If you're behind a corporate proxy, make sure to [configure it properly](https://on.cypress.io/proxy-configuration) before install.
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: A description including screenshots, stack traces, DEBUG logs, etc. [Troubleshooting tips](https://on.cypress.io/troubleshooting).
      placeholder: When I try to download Cypress...
    validations:
      required: true
  - type: textarea
    id: debug-logs
    attributes:
      label: Debug logs
      description: Include DEBUG logs setting [`DEBUG=cypress:*`](https://on.cypress.io/troubleshooting#Print-DEBUG-logs/). Include npm/yarn logs if applicable.
      placeholder: Debug logs
  - type: input
    id: version
    attributes:
      label: Cypress Version
      description: The version you're trying to install
      placeholder: ex. 7.6.0
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      options:
        - npm
        - yarn
        - Direct download
        - pnpm
        - other
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      options:
        - Linux
        - Mac
        - Windows
        - other
    validations:
      required: true
  - type: textarea
    id: othter
    attributes:
      label: Other
      placeholder: Any other details?