name: "❄️ Flaky test in `cypress-io/cypress` repository"
title: "Flaky test: "
labels: ["topic: flake ❄️", "stage: fire watch"]
description: Report a flaky test in the Cypress open-source repository.
body:
  - type: markdown
    attributes:
      value: |
        Have a question? 👉 [Start a new discussion](https://github.com/cypress-io/cypress/discussions) or [ask in chat](https://on.cypress.io/discord).
  - type: textarea
    id: dashboard
    attributes:
      label: Link to dashboard or CircleCI failure
      description: Please include a link to the failure in the Cypress Dashboard or in CircleCI.
    validations:
      required: true
  - type: textarea
    id: github-link
    attributes:
      label: Link to failing test in GitHub
      description: Provide the GitHub link to the failing test with the line number.
    validations:
      required: true
  - type: textarea
    id: analysis
    attributes:
      label: Analysis
      description: If you can, provide a quick analysis of why this test is flaky. 
      placeholder: ex. The test appears to be flaky because...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Cypress Version
      description: Provide the version of Cypress where the flake is occurring.
      placeholder: ex. 10.4.0
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other
      placeholder: Any other details?
