blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/cypress-io/cypress/discussions
    about: This issue tracker is not for support questions. Please refer to our Discussions.
  - name: 💬 Chat
    url: https://on.cypress.io/discord
    about: Want to discuss Cypress with others? Check out our chat.
  - name: 📃 Documentation Issue
    url: https://github.com/cypress-io/cypress-documentation/issues/new
    about: This issue tracker is not for documentation issues. Please open documentation issues here.

