// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'appWrapper': string;
  'appWrapperScreenshotting': string;
  'ctDevtoolsContainer': string;
  'ctPluginToggleButton': string;
  'ctPlugins': string;
  'ctPluginsHeader': string;
  'ctPluginsName': string;
  'ctTogglePluginsSectionButton': string;
  'ctTogglePluginsSectionButtonOpen': string;
  'display-none': string;
  'folder': string;
  'largerIcon': string;
  'leftNav': string;
  'noSpecAut': string;
  'noSpecsDescription': string;
  'reporter': string;
  'runner': string;
  'runnerCt': string;
  'screenshotting': string;
  'size-container': string;
}
export const cssExports: CssExports;
export default cssExports;
