resource_class: small
docker:
  - image: cimg/node:current
steps:
  - checkout
  - continuation/continue:
      configuration_path: .circleci/workflows.yml
      parameters: '{ "approved_contributor_pr": true }'
