// Generated by CoffeeScript 2.2.1
(function() {
  // just an example of transpilation w/ sourcemap -
  // `test.coffee` is not directly transpiled/executed by any test code
  // regenerate JS + sourcemap with `coffee -c -m test.coffee`
  setTimeout(function() {
    window;
    var foo;
    return foo = `${window.top.foo}`;
  }, 1000);

}).call(this);

//# sourceMappingURL=test.js.map
