export const snapshots = {
  'test-retry-with-hooks.retries.mochaEvents.cy.js': [
    'start',
    'suite',
    'suite',
    'hook',
    'test:before:run',
    'hook end',
    'test',
    'hook',
    'hook end',
    'retry',
    'hook',
    'hook end',
    'test:after:run',
    'hook',
    'test:before:run',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'suite end',
    'test:after:run',
    'suite end',
    'end',
  ],

  'test-retry-with-only.retries.mochaEvents.cy.js': [
    'start',
    'suite',
    'suite',
    'hook',
    'test:before:run',
    'hook end',
    'test',
    'hook',
    'hook end',
    'retry',
    'hook',
    'hook end',
    'test:after:run',
    'hook',
    'test:before:run',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'suite end',
    'test:after:run',
    'suite end',
    'end',
  ],

  'can-retry-from-beforeEach.retries.mochaEvents.cy.js': [
    'start',
    'suite',
    'suite',
    'hook',
    'test:before:run',
    'hook end',
    'test',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'retry',
    'hook',
    'hook end',
    'test:after:run',
    'hook',
    'test:before:run',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'suite end',
    'test:after:run',
    'suite end',
    'end',
  ],

  'can-retry-from-afterEach.retries.mochaEvents.cy.js': [
    'start',
    'suite',
    'suite',
    'hook',
    'test:before:run',
    'hook end',
    'test',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'retry',
    'hook end',
    'test:after:run',
    'hook',
    'test:before:run',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'test:after:run',
    'test',
    'hook',
    'test:before:run',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'test:after:run',
    'test',
    'hook',
    'test:before:run',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'test:after:run',
    'suite end',
    'suite',
    'test',
    'test:before:run',
    'hook',
    'retry',
    'hook end',
    'hook',
    'hook end',
    'test:after:run',
    'test:before:run',
    'hook',
    'retry',
    'hook end',
    'hook',
    'hook end',
    'test:after:run',
    'test:before:run',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'test:after:run',
    'suite end',
    'suite',
    'test',
    'test:before:run',
    'hook',
    'hook end',
    'pass',
    'test end',
    'suite end',
    'test:after:run',
    'suite end',
    'end',
  ],

  'cant-retry-from-before.retries.mochaEvents.cy.js': [
    'start',
    'suite',
    'suite',
    'hook',
    'test:before:run',
    'fail',
    'hook',
    'hook end',
    'suite end',
    'test end',
    'test:after:run',
    'suite end',
    'end',
  ],

  'cant-retry-from-after.retries.mochaEvents.cy.js': [
    'start',
    'suite',
    'suite',
    'hook',
    'test:before:run',
    'hook end',
    'test',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'fail',
    'test end',
    'suite end',
    'test:after:run',
    'suite end',
    'end',
  ],

  'three-tests-with-retry.retries.mochaEvents.cy.js': [
    'start',
    'suite',
    'suite',
    'hook',
    'test:before:run',
    'hook end',
    'test',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'test:after:run',
    'test',
    'hook',
    'test:before:run',
    'hook end',
    'retry',
    'hook',
    'hook end',
    'test:after:run',
    'hook',
    'test:before:run',
    'hook end',
    'retry',
    'hook',
    'hook end',
    'test:after:run',
    'hook',
    'test:before:run',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'test:after:run',
    'test',
    'hook',
    'test:before:run',
    'hook end',
    'hook',
    'hook end',
    'hook',
    'hook end',
    'pass',
    'test end',
    'suite end',
    'test:after:run',
    'suite end',
    'end',
  ],

  'does-not-serialize-dom-error.cy.js': [
    'start',
    'suite',
    'test',
    'test:before:run',
    'retry',
    'test:after:run',
    'test:before:run',
    'retry',
    'test:after:run',
    'test:before:run',
    'fail',
    'test end',
    'test:after:run',
    'suite end',
    'end',
  ],
} as const
