import { baseConfig } from '@packages/eslint-config'

export default [
  {
    // tsc output, regenerated by `yarn build`
    ignores: ['cjs/**', 'esm/**'],
  },
  ...baseConfig,
  {
    files: ['**/*.spec.ts', '**/*.ts'],
    languageOptions: {
      parserOptions: {
        tsconfigRootDir: __dirname,
      },
    },
  },
]
