export * from './types'

import {
  getParentNode,
  getParent,
  getAllParents,
  findParent,
  getFirstParentWithTagName,
  getFirstCommonAncestor,
  getFirstDeepestElement,
  elementFromPoint,
  isAncestor,
  isChild,
  isDescendent,
  isUndefinedOrHTMLBodyDoc,
  getElements,
  getContainsSelector,
  getInputFromLabel,
} from './find'

import {
  isDisabled,
  isButtonLike,
  isTextLike,
  isFocused,
  isFocusable,
  isFocusedOrInFocused,
  isFocusableWhenNotDisabled,
  getFirstFocusableEl,
  getActiveElByDocument,
  isScrollable,
  getFirstFixedOrStickyPositionParent,
  getFirstStickyPositionParent,
  getFirstScrollableParent,
  elOrAncestorIsFixedOrSticky,
  canSetSelectionRangeElement,
} from './complexElements'

import {
  isShadowRoot,
  isWithinShadowRoot,
  getShadowElementFromPoint,
  getShadowRoot,
  findAllShadowRoots,
} from './shadow'

import {
  getTagName,
  isElement,
  isInput,
  isTextarea,
  isButton,
  isSelect,
  isOption,
  isOptgroup,
  isBody,
  isIframe,
  isHTML,
  isSvg,
  isValueNumberTypeElement,
  isNeedSingleValueChangeInputElement,
  isAttrType,
} from './elementHelpers'

import {
  tryCallNativeMethod,
  callNativeMethod,
  getNativeProp,
  setNativeProp,
} from './nativeProps'

import {
  isInputType,
  isReadOnlyInputOrTextarea,
  isReadOnlyInput,
  isInputAllowingImplicitFormSubmission,
} from './input'

import {
  isContentEditable,
  hasContenteditableAttr,
  getHostContenteditable,
  isDesignModeDocumentElement,
} from './contentEditable'

import {
  isDetached,
  isAttached,
  isDetachedEl,
  isAttachedEl,
} from './detached'

import {
  normalizeWhitespaces,
  isSame,
  isSelector,
  switchCase,
  stringify,
} from './utils'

export default {
  getParentNode,
  getParent,
  getAllParents,
  findParent,
  getFirstParentWithTagName,
  getFirstCommonAncestor,
  getFirstDeepestElement,
  elementFromPoint,
  isAncestor,
  isChild,
  isDescendent,
  isUndefinedOrHTMLBodyDoc,
  getElements,
  getContainsSelector,
  getInputFromLabel,
  isDisabled,
  isButtonLike,
  isTextLike,
  isFocused,
  isFocusable,
  isFocusedOrInFocused,
  isFocusableWhenNotDisabled,
  getFirstFocusableEl,
  getActiveElByDocument,
  isScrollable,
  getFirstFixedOrStickyPositionParent,
  getFirstStickyPositionParent,
  getFirstScrollableParent,
  elOrAncestorIsFixedOrSticky,
  canSetSelectionRangeElement,
  isShadowRoot,
  isWithinShadowRoot,
  getShadowElementFromPoint,
  getShadowRoot,
  findAllShadowRoots,
  getTagName,
  isElement,
  isInput,
  isTextarea,
  isButton,
  isSelect,
  isOption,
  isOptgroup,
  isBody,
  isIframe,
  isHTML,
  isSvg,
  isValueNumberTypeElement,
  isNeedSingleValueChangeInputElement,
  isAttrType,
  tryCallNativeMethod,
  callNativeMethod,
  getNativeProp,
  setNativeProp,
  isInputType,
  isReadOnlyInputOrTextarea,
  isReadOnlyInput,
  isInputAllowingImplicitFormSubmission,
  isContentEditable,
  hasContenteditableAttr,
  getHostContenteditable,
  isDesignModeDocumentElement,
  isDetached,
  isAttached,
  isDetachedEl,
  isAttachedEl,
  normalizeWhitespaces,
  isSame,
  isSelector,
  switchCase,
  stringify,
}
