exports['src/index .getBreakingKeys returns list of breaking config keys 1'] = [
  "blacklistHosts",
  "componentFolder",
  "integrationFolder",
  "testFiles",
  "ignoreTestFiles",
  "experimentalComponentTesting",
  "experimentalGetCookiesSameSite",
  "experimentalNetworkStubbing",
  "experimentalRunEvents",
  "experimentalShadowDomSupport",
  "experimentalStudio",
  "firefoxGcInterval",
  "nodeVersion",
  "nodeVersion",
  "pluginsFile"
]

exports['src/index .getDefaultValues returns list of public config keys 1'] = {
  "animationDistanceThreshold": 5,
  "baseUrl": null,
  "blockHosts": null,
  "chromeWebSecurity": true,
  "clientCertificates": [],
  "component": {
    "specPattern": "**/*.cy.{js,jsx,ts,tsx}",
    "indexHtmlFile": "cypress/support/component-index.html"
  },
  "defaultCommandTimeout": 4000,
  "downloadsFolder": "cypress/downloads",
  "e2e": {
    "specPattern": "cypress/e2e/**/*.cy.{js,jsx,ts,tsx}"
  },
  "env": {},
  "execTimeout": 60000,
  "exit": true,
  "experimentalFetchPolyfill": false,
  "experimentalInteractiveRunEvents": false,
  "experimentalSessionSupport": false,
  "experimentalSourceRewriting": false,
  "fileServerFolder": "",
  "fixturesFolder": "cypress/fixtures",
  "excludeSpecPattern": "*.hot-update.js",
  "includeShadowDom": false,
  "keystrokeDelay": 0,
  "modifyObstructiveCode": true,
  "numTestsKeptInMemory": 50,
  "pageLoadTimeout": 60000,
  "port": null,
  "projectId": null,
  "redirectionLimit": 20,
  "reporter": "spec",
  "reporterOptions": null,
  "requestTimeout": 5000,
  "resolvedNodePath": null,
  "resolvedNodeVersion": null,
  "responseTimeout": 30000,
  "retries": {
    "runMode": 0,
    "openMode": 0
  },
  "screenshotOnRunFailure": true,
  "screenshotsFolder": "cypress/screenshots",
  "slowTestThreshold": 10000,
  "scrollBehavior": "top",
  "supportFile": "cypress/support/e2e.{js,jsx,ts,tsx}",
  "supportFolder": false,
  "taskTimeout": 60000,
  "trashAssetsBeforeRuns": true,
  "userAgent": null,
  "video": true,
  "videoCompression": 32,
  "videosFolder": "cypress/videos",
  "videoUploadOnPasses": true,
  "viewportHeight": 660,
  "viewportWidth": 1000,
  "waitForAnimations": true,
  "watchForFileChanges": true,
  "autoOpen": false,
  "browsers": [],
  "clientRoute": "/__/",
  "configFile": "cypress.config.js",
  "devServerPublicPathRoute": "/__cypress/src",
  "hosts": null,
  "isInteractive": true,
  "isTextTerminal": false,
  "morgan": true,
  "namespace": "__cypress",
  "reporterRoute": "/__cypress/reporter",
  "socketId": null,
  "socketIoCookie": "__socket",
  "socketIoRoute": "/__socket",
  "xhrRoute": "/xhrs/"
}

exports['src/index .getPublicConfigKeys returns list of public config keys 1'] = [
  "animationDistanceThreshold",
  "arch",
  "baseUrl",
  "blockHosts",
  "chromeWebSecurity",
  "clientCertificates",
  "component",
  "defaultCommandTimeout",
  "downloadsFolder",
  "e2e",
  "env",
  "execTimeout",
  "exit",
  "experimentalFetchPolyfill",
  "experimentalInteractiveRunEvents",
  "experimentalSessionSupport",
  "experimentalSourceRewriting",
  "fileServerFolder",
  "fixturesFolder",
  "excludeSpecPattern",
  "includeShadowDom",
  "keystrokeDelay",
  "modifyObstructiveCode",
  "nodeVersion",
  "numTestsKeptInMemory",
  "platform",
  "pageLoadTimeout",
  "port",
  "projectId",
  "redirectionLimit",
  "reporter",
  "reporterOptions",
  "requestTimeout",
  "resolvedNodePath",
  "resolvedNodeVersion",
  "responseTimeout",
  "retries",
  "screenshotOnRunFailure",
  "screenshotsFolder",
  "slowTestThreshold",
  "scrollBehavior",
  "supportFile",
  "supportFolder",
  "taskTimeout",
  "trashAssetsBeforeRuns",
  "userAgent",
  "video",
  "videoCompression",
  "videosFolder",
  "videoUploadOnPasses",
  "viewportHeight",
  "viewportWidth",
  "waitForAnimations",
  "watchForFileChanges",
  "browsers",
  "hosts",
  "isInteractive",
  "modifyObstructiveCode",
  "specPattern"
]
