export const longBrowsersList = [
  {
    id: '1',
    name: 'electron',
    displayName: 'Electron',
    family: 'chromium',
    channel: 'stable',
    version: '73.0.3683.121',
    path: '',
    majorVersion: '73',
    info: 'Info about electron browser',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: false,
  },
  {
    id: '2',
    name: 'chrome',
    displayName: 'Chrome',
    family: 'chromium',
    channel: 'stable',
    version: '78.0.3904.108',
    path: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    majorVersion: '78',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: false,
  },
  {
    id: '3',
    name: 'chrome',
    displayName: 'Chrome',
    family: 'chromium',
    channel: 'stable',
    version: '88.0.3904.00',
    path: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    majorVersion: '88',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: false,
  },
  {
    id: '4',
    name: 'chrome',
    displayName: 'Canary',
    family: 'chromium',
    channel: 'canary',
    version: '80.0.3977.4',
    path: '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
    majorVersion: '80',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: false,
  },
  {
    id: '5',
    name: 'chromium',
    displayName: 'Chromium',
    family: 'chromium',
    channel: 'stable',
    version: '74.0.3729.0',
    path: '/Applications/Chromium.app/Contents/MacOS/Chromium',
    majorVersion: '74',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: false,
  },
  {
    id: '6',
    name: 'chromium',
    displayName: 'Chromium',
    family: 'chromium',
    channel: 'stable',
    version: '85.0.3729.0',
    path: '/Applications/Chromium.app/Contents/MacOS/Chromium',
    majorVersion: '85',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: false,
  },
  {
    id: '7',
    name: 'edge',
    displayName: 'Edge Beta',
    family: 'chromium',
    channel: 'beta',
    version: '85.0.309.71',
    path: '/Applications/Microsoft Edge Beta.app/Contents/MacOS/Microsoft Edge Beta',
    majorVersion: '85',
    isFocusSupported: true,
    isVersionSupported: false,
    disabled: false,
  },
  {
    id: '8',
    name: 'edge',
    displayName: 'Edge Canary',
    family: 'chromium',
    channel: 'canary',
    version: '79.0.309.71',
    path: '/Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary',
    majorVersion: '79',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: false,
  },
  {
    id: '9',
    name: 'edge',
    displayName: 'Edge Dev',
    family: 'chromium',
    channel: 'dev',
    version: '80.0.309.71',
    path: '/Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev',
    majorVersion: '79',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: false,
  },
  {
    id: '10',
    name: 'firefox',
    displayName: 'Firefox',
    family: 'firefox',
    channel: 'stable',
    version: '69.0.1',
    path: '/Applications/Firefox/Contents/MacOS/Firefox',
    majorVersion: '69',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: true,
  },
  {
    id: '11',
    name: 'firefox',
    displayName: 'Firefox',
    family: 'firefox',
    channel: 'stable',
    version: '75.0.1',
    path: '/Applications/Firefox/Contents/MacOS/Firefox',
    majorVersion: '75',
    isFocusSupported: true,
    isVersionSupported: true,
    disabled: true,
  },
  {
    id: '12',
    name: 'firefox',
    displayName: 'Firefox Developer Edition',
    channel: 'dev',
    family: 'firefox',
    version: '69.0.2',
    path: '/Applications/Firefox Developer/Contents/MacOS/Firefox Developer',
    majorVersion: '69',
    isFocusSupported: true,
    isVersionSupported: false,
    disabled: true,
    warning: 'Cypress does not support running Firefox Developer Edition version 69. To use Firefox Developer Edition with Cypress, install a version of Firefox Developer Edition newer than or equal to 78.',
  },
  {
    id: '13',
    name: 'firefox',
    displayName: 'Firefox Nightly',
    channel: 'beta',
    family: 'firefox',
    version: '69.0.3',
    path: '/Applications/Firefox Nightly/Contents/MacOS/Firefox Nightly',
    majorVersion: '69',
    isFocusSupported: false,
    isVersionSupported: true,
    disabled: true,
  },
  {
    id: '14',
    name: 'fake',
    displayName: 'Fake Browser',
    channel: 'stable',
    family: 'chromium',
    version: '79.0.309.71',
    path: '/Applications/Fake Browser/Contents/MacOS/Fake Browser',
    majorVersion: '79',
    isFocusSupported: false,
    isVersionSupported: true,
    disabled: true,
  },
] as const
