import { Configuration } from "webpack";

interface BabelDevServerOptions {
  /**
   * Allows to adjust the webpackConfig that our dev-server will use
   * @param config configuration generated by the plugin
   * @returns modified final configuration
   */
  setWebpackConfig?(config:Configuration): Configuration
}

/**
 * Setup a webpack dev server with the proper configuration for babel transpilation
 * @param on comes from the argument of the `pluginsFile` function
 * @param config comes from the argument of the `pluginsFile` function
 * @param options additional options object (create an empty object it to see how to use it)
 */
declare function legacySetupBabelDevServer(on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions, options?: BabelDevServerOptions): void

declare namespace legacySetupBabelDevServer {
  /**
   * Sets up a webpack dev server with the proper configuration for babel transpilation
   * @param devServerConfig comes from the `setupDevServer()` function first argument
   * @param options additional options object (create an empty object to see how to use it)
   * @returns the resolved dev server object that cypress can use to start testing
   */
  export function setupBabelDevServer(devServerConfig: Cypress.DevServerConfig, options?: BabelDevServerOptions): Cypress.ResolvedDevServerConfig
}

export = legacySetupBabelDevServer;