version: 2.1

commands:
  early-stop:
    description: |
      Early halt if this commit is for testing binaries for different platform
      Place this command AFTER checkout command because we need to look
      at the commit subject text
    parameters:
      substring:
        type: string
        description: String to search for in the commit subject to skip build
    steps:
      - run:
          name: Checking OS platform for "<< parameters.substring >>"
          command: |
            subject=$(git show -s --pretty=%s)
            echo "Commit subject: $subject"

            if [[ $subject == *"<< parameters.substring >>"* ]]; then
              echo Skipping testing binary ⏭
              echo Found string "<< parameters.substring >>"
              circleci step halt
            fi

jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - early-stop:
          # we should not test Mac binary on Linux machines
          substring: Testing new darwin
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm install @cypress/commit-message-install
      # now install just a specific version of Cypress (from commit message)
      # or latest version of Cypress
      - run:
          name: Install Cypress
          command: $(npm bin)/commit-message-install --else "npm i cypress"
      - run: npm run cy:verify
      - run: node index.js
      - run: node async.js
      - run: npm test
      # set commit status if necessary
      - run:
          when: on_success
          name: Set status check
          command: $(npm bin)/set-status --state success --description "on CircleCI"
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "on CircleCI"

workflows:
  version: 2
  build:
    jobs:
      - test:
          context: test-runner:commit-status-checks
