/* eslint-disable */
// Generated by codegen-mount-ts.ts, do not edit directly
import type { NexusGenObjects, NexusGenInterfaces } from '@packages/graphql/src/gen/nxs.gen'
export interface TestSourceTypeLookup {
  App: NexusGenObjects['App'],
  Browser: NexusGenObjects['Browser'],
  CloudOrganization: NexusGenObjects['CloudOrganization'],
  CloudOrganizationConnection: NexusGenObjects['CloudOrganizationConnection'],
  CloudOrganizationEdge: NexusGenObjects['CloudOrganizationEdge'],
  CloudProject: NexusGenObjects['CloudProject'],
  CloudProjectConnection: NexusGenObjects['CloudProjectConnection'],
  CloudProjectEdge: NexusGenObjects['CloudProjectEdge'],
  CloudRecordKey: NexusGenObjects['CloudRecordKey'],
  CloudRun: NexusGenObjects['CloudRun'],
  CloudRunCommitInfo: NexusGenObjects['CloudRunCommitInfo'],
  CloudRunConnection: NexusGenObjects['CloudRunConnection'],
  CloudRunEdge: NexusGenObjects['CloudRunEdge'],
  CloudUser: NexusGenObjects['CloudUser'],
  Mutation: NexusGenObjects['Mutation'],
  NavigationItem: NexusGenObjects['NavigationItem'],
  NavigationMenu: NexusGenObjects['NavigationMenu'],
  Node: NexusGenInterfaces['Node'],
  PageInfo: NexusGenObjects['PageInfo'],
  Project: NexusGenObjects['Project'],
  Query: NexusGenObjects['Query'],
  ResolvedBooleanOption: NexusGenObjects['ResolvedBooleanOption'],
  ResolvedConfig: NexusGenObjects['ResolvedConfig'],
  ResolvedJsonOption: NexusGenObjects['ResolvedJsonOption'],
  ResolvedNumberOption: NexusGenObjects['ResolvedNumberOption'],
  ResolvedOptionBase: NexusGenInterfaces['ResolvedOptionBase'],
  ResolvedStringListOption: NexusGenObjects['ResolvedStringListOption'],
  ResolvedStringOption: NexusGenObjects['ResolvedStringOption'],
  TestingTypeInfo: NexusGenObjects['TestingTypeInfo'],
  Wizard: NexusGenObjects['Wizard'],
  WizardBundler: NexusGenObjects['WizardBundler'],
  WizardFrontendFramework: NexusGenObjects['WizardFrontendFramework'],
  WizardNpmPackage: NexusGenObjects['WizardNpmPackage'],
}

import { list, nonNull, queryField, unionType } from 'nexus'

export const testUnionType = unionType({
  name: 'TestUnion',
  definition (t) {
    // !!! Generated by codegen-mount-ts.ts, do not edit directly !!!
    t.members(
      'App',
      'Browser',
      'CloudOrganization',
      'CloudOrganizationConnection',
      'CloudOrganizationEdge',
      'CloudProject',
      'CloudProjectConnection',
      'CloudProjectEdge',
      'CloudRecordKey',
      'CloudRun',
      'CloudRunCommitInfo',
      'CloudRunConnection',
      'CloudRunEdge',
      'CloudUser',
      'Mutation',
      'NavigationItem',
      'NavigationMenu',
      'PageInfo',
      'Project',
      'Query',
      'ResolvedBooleanOption',
      'ResolvedConfig',
      'ResolvedJsonOption',
      'ResolvedNumberOption',
      'ResolvedStringListOption',
      'ResolvedStringOption',
      'TestingTypeInfo',
      'Wizard',
      'WizardBundler',
      'WizardFrontendFramework',
      'WizardNpmPackage'
    )
    // !!! Generated by codegen-mount-ts.ts, do not edit directly !!!
  },
  resolveType (c) {
    // @ts-ignore
    return c.__typename ?? c.constructor.name
  },
})

// !!! Generated by codegen-mount-ts.ts, do not edit directly !!!
export const testFragmentMember = queryField('testFragmentMember', {
  description: 'Provides a fragment target for testing',
  type: nonNull(testUnionType),
  resolve: (source) => {
    return source
  }
})

// !!! Generated by codegen-mount-ts.ts, do not edit directly !!!
export const testFragmentMemberList = queryField('testFragmentMemberList', {
  description: 'Provides a fragment target list for testing',
  type: list(nonNull(testUnionType)),
  resolve: (source) => {
    return source
  }
})
