/* eslint-disable */
// Generated by codegen-mount-ts.ts, do not edit directly
import type { NexusGenObjects } from '@packages/graphql/src/gen/nxs.gen'
export type SourceTypeLookup<T extends string> = T extends keyof NexusGenObjects ? NexusGenObjects[T] : unknown
export interface TestSourceTypeLookup {
  App: SourceTypeLookup<'App'>,
  Browser: SourceTypeLookup<'Browser'>,
  CloudEdge: SourceTypeLookup<'CloudEdge'>,
  CloudOrganization: SourceTypeLookup<'CloudOrganization'>,
  CloudProject: SourceTypeLookup<'CloudProject'>,
  CloudProjectConnection: SourceTypeLookup<'CloudProjectConnection'>,
  CloudProjectEdge: SourceTypeLookup<'CloudProjectEdge'>,
  CloudQuery: SourceTypeLookup<'CloudQuery'>,
  CloudRecordKey: SourceTypeLookup<'CloudRecordKey'>,
  CloudRun: SourceTypeLookup<'CloudRun'>,
  CloudRunCommitInfo: SourceTypeLookup<'CloudRunCommitInfo'>,
  CloudRunConnection: SourceTypeLookup<'CloudRunConnection'>,
  CloudRunEdge: SourceTypeLookup<'CloudRunEdge'>,
  CloudUser: SourceTypeLookup<'CloudUser'>,
  Mutation: SourceTypeLookup<'Mutation'>,
  NavigationItem: SourceTypeLookup<'NavigationItem'>,
  NavigationMenu: SourceTypeLookup<'NavigationMenu'>,
  Node: SourceTypeLookup<'Node'>,
  PageInfo: SourceTypeLookup<'PageInfo'>,
  Project: SourceTypeLookup<'Project'>,
  Query: SourceTypeLookup<'Query'>,
  ResolvedBooleanOption: SourceTypeLookup<'ResolvedBooleanOption'>,
  ResolvedConfig: SourceTypeLookup<'ResolvedConfig'>,
  ResolvedJsonOption: SourceTypeLookup<'ResolvedJsonOption'>,
  ResolvedNumberOption: SourceTypeLookup<'ResolvedNumberOption'>,
  ResolvedOptionBase: SourceTypeLookup<'ResolvedOptionBase'>,
  ResolvedStringListOption: SourceTypeLookup<'ResolvedStringListOption'>,
  ResolvedStringOption: SourceTypeLookup<'ResolvedStringOption'>,
  TestingTypeInfo: SourceTypeLookup<'TestingTypeInfo'>,
  Viewer: SourceTypeLookup<'Viewer'>,
  Wizard: SourceTypeLookup<'Wizard'>,
  WizardBundler: SourceTypeLookup<'WizardBundler'>,
  WizardFrontendFramework: SourceTypeLookup<'WizardFrontendFramework'>,
  WizardNpmPackage: SourceTypeLookup<'WizardNpmPackage'>,
}

import { list, nonNull, queryField, unionType } from 'nexus'

export const testUnionType = unionType({
  name: 'TestUnion',
  definition (t) {
    // !!! Generated by codegen-mount-ts.ts, do not edit directly !!!
    t.members(
      'App',
      'Browser',
      'CloudOrganization',
      'CloudProject',
      'CloudProjectConnection',
      'CloudProjectEdge',
      'CloudQuery',
      'CloudRecordKey',
      'CloudRun',
      'CloudRunCommitInfo',
      'CloudRunConnection',
      'CloudRunEdge',
      'CloudUser',
      'Mutation',
      'NavigationItem',
      'NavigationMenu',
      'PageInfo',
      'Project',
      'Query',
      'ResolvedBooleanOption',
      'ResolvedConfig',
      'ResolvedJsonOption',
      'ResolvedNumberOption',
      'ResolvedOptionBase',
      'ResolvedStringListOption',
      'ResolvedStringOption',
      'TestingTypeInfo',
      'Viewer',
      'Wizard',
      'WizardBundler',
      'WizardFrontendFramework',
      'WizardNpmPackage'
    )
    // !!! Generated by codegen-mount-ts.ts, do not edit directly !!!
  },
  resolveType (c) {
    // @ts-ignore
    return c.__typename ?? c.constructor.name
  },
})

// !!! Generated by codegen-mount-ts.ts, do not edit directly !!!
export const testFragmentMember = queryField('testFragmentMember', {
  description: 'Provides a fragment target for testing',
  type: nonNull(testUnionType),
  resolve: (source) => {
    return source
  }
})

// !!! Generated by codegen-mount-ts.ts, do not edit directly !!!
export const testFragmentMemberList = queryField('testFragmentMemberList', {
  description: 'Provides a fragment target list for testing',
  type: list(nonNull(testUnionType)),
  resolve: (source) => {
    return source
  }
})
