exports['browsers returns the expected list of browsers 1'] = [
  {
    'name': 'chrome',
    'family': 'chromium',
    'channel': 'stable',
    'displayName': 'Chrome',
    'versionRegex': {},
    'binary': [
      'google-chrome',
      'chrome',
      'google-chrome-stable',
    ],
  },
  {
    'name': 'chrome',
    'family': 'chromium',
    'channel': 'beta',
    'displayName': 'Chrome Beta',
    'versionRegex': {},
    'binary': 'google-chrome-beta',
  },
  {
    'name': 'chrome',
    'family': 'chromium',
    'channel': 'canary',
    'displayName': 'Chrome Canary',
    'versionRegex': {},
    'binary': 'google-chrome-canary',
  },
  {
    'name': 'chrome-for-testing',
    'family': 'chromium',
    'channel': 'stable',
    'displayName': 'Chrome for Testing',
    'versionRegex': {},
    'binary': 'chrome',
  },
  {
    'name': 'chromium',
    'family': 'chromium',
    'channel': 'stable',
    'displayName': 'Chromium',
    'versionRegex': {},
    'binary': [
      'chromium-browser',
      'chromium',
    ],
  },
  {
    'name': 'firefox',
    'family': 'firefox',
    'channel': 'stable',
    'displayName': 'Firefox',
    'versionRegex': {},
    'binary': 'firefox',
  },
  {
    'name': 'firefox',
    'family': 'firefox',
    'channel': 'dev',
    'displayName': 'Firefox Developer Edition',
    'versionRegex': {},
    'binary': [
      'firefox-developer-edition',
      'firefox',
    ],
  },
  {
    'name': 'firefox',
    'family': 'firefox',
    'channel': 'nightly',
    'displayName': 'Firefox Nightly',
    'versionRegex': {},
    'binary': [
      'firefox-nightly',
      'firefox-trunk',
    ],
  },
  {
    'name': 'edge',
    'family': 'chromium',
    'channel': 'stable',
    'displayName': 'Edge',
    'versionRegex': {},
    'binary': [
      'edge',
      'microsoft-edge',
    ],
  },
  {
    'name': 'edge',
    'family': 'chromium',
    'channel': 'beta',
    'displayName': 'Edge Beta',
    'versionRegex': {},
    'binary': [
      'edge-beta',
      'microsoft-edge-beta',
    ],
  },
  {
    'name': 'edge',
    'family': 'chromium',
    'channel': 'canary',
    'displayName': 'Edge Canary',
    'versionRegex': {},
    'binary': [
      'edge-canary',
      'microsoft-edge-canary',
    ],
  },
  {
    'name': 'edge',
    'family': 'chromium',
    'channel': 'dev',
    'displayName': 'Edge Dev',
    'versionRegex': {},
    'binary': [
      'edge-dev',
      'microsoft-edge-dev',
    ],
  },
]
