export default {
  LOADING: 'LOADING',
  LOGIN: 'LOGIN',
  APPLYING_UPDATES: 'APPLYING_UPDATES',
  INTRO: 'INTRO',
  PROJECT_SPECS: 'PROJECT_SPECS',
  PROJECT_RUNS: 'PROJECT_RUNS',
  PROJECT_SETTINGS: 'PROJECT_SETTINGS',
}
