export default {
  LOADING: 'LOADING',
  LOGIN: 'LOGIN',
  APPLYING_UPDATES: 'APPLYING_UPDATES',
  APP: 'APP',
  PROJECTS: 'PROJECTS',
  PROJECT_SPECS: 'PROJECT_SPECS',
  PROJECT_RUNS: 'PROJECT_RUNS',
  PROJECT_CONFIG: 'PROJECT_CONFIG',
}
