name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-reply:
    runs-on: ubuntu-latest
    steps:
      - name: needs information
        if: github.event.label.name == 'stage: needs information'
        uses: actions-cool/issues-helper@v1.8
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Can you provide a reproducible example of the issue? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress guide](https://docs.cypress.io/guides/references/troubleshooting.html).
