name: merge-master-into-develop
on:
  push:
    branches:
      - master
jobs:
  merge-master-into-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout develop branch
        run: git checkout develop
      - name: Set committer email
        run: git config --local user.email "$(git log --format='%ae' HEAD^!)"
      - name: Set committer name
        run: git config --local user.name "$(git log --format='%an' HEAD^!)"
      - name: Check for merge conflict
        id: check-conflict
        run: echo "::set-output name=merge_conflict::$(git merge-tree $(git merge-base HEAD master) master HEAD | egrep '<<')"
      - name: Merge master into develop
        run: git merge master
        if: ${{ !steps.check-conflict.outputs.merge_conflict }}
      - name: Push
        run: git push
        if: ${{ !steps.check-conflict.outputs.merge_conflict }}
      - name: Determine name of new branch
        id: new-branch-name
        run: echo "::set-output name=branch_name::$(git rev-parse --short HEAD)-master-into-develop"
        if: ${{ steps.check-conflict.outputs.merge_conflict }}
      - name: Create a copy of master on a new branch
        run: git checkout -b ${{ steps.new-branch-name.outputs.branch_name }} master
        if: ${{ steps.check-conflict.outputs.merge_conflict }}
      - name: Push branch to remote
        run: git push origin ${{ steps.new-branch-name.outputs.branch_name }}
        if: ${{ steps.check-conflict.outputs.merge_conflict }}
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.new-branch-name.outputs.branch_name }}
          destination_branch: "develop"
          pr_title: "Merge branch 'master' into develop"
          pr_body: "There was a merge conflict when trying to automatically merge master into develop. Please resolve the conflict and complete the merge."
        if: ${{ steps.check-conflict.outputs.merge_conflict }}
