name: 'Triage: add issue/PR to project'

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  add-to-triage-project:
    name: Add to triage project
    runs-on: ubuntu-latest
    env:
      PROJECT_NUMBER: 9
      GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
    steps:
      - name: is-collaborator
        run: |
          gh api graphql -f query='
            query($org: String!, $repo: String!, $user: String!) {
              repository(owner: $org, name: $repo) {
                collaborators(query: $user, first: 1) {
                  totalCount
                }
              }
            } ' -f org=${{ github.repository_owner }} -f repo=${{ github.event.repository.name }} -f user=${{ github.actor }} > collaborators.json

          echo 'IS_COLLABORATOR='$(jq -r '.data.repository.collaborators.totalCount' collaborators.json) >> $GITHUB_ENV
      - uses: actions/add-to-project@v0.4.0
        # only add issues/prs from outside contributors to the project
        if: ${{ env.IS_COLLABORATOR == 0 }}
        with:
          project-url: https://github.com/orgs/${{github.repository_owner}}/projects/${{env.PROJECT_NUMBER}}
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
