name: 'Handle Issue/PR Comment Workflow'
on:
  # makes this workflow reusable
  workflow_call:
    secrets:
      TRIAGE_BOARD_TOKEN:
        required: true

  issue_comment:
    types: [created]

permissions: {}

jobs:
  handle-comment-scenarios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          repository: 'cypress-io/release-automations'
          ref: 'fa3826c4388bf0964e8507ab74cba78ffe9e83a8' # master
          ssh-key: ${{ secrets.WORKFLOW_DEPLOY_KEY }} 
      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 'lts/*'
      - name: Run comment_workflow.js Script
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          github-token: ${{ secrets.TRIAGE_BOARD_TOKEN }}
          script: |
            const script = require('./scripts/triage/comment_workflow.js')
            await script.handleComment(github, context);
