name: "Trigger CircleCi Pipeline"

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize

jobs:
  main:
    name: Trigger CircleCi Pipeline when PR is ready for review
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.pull_request.draft == true }} 
        run: echo "This PR is still in draft. Not triggering the CircleCi Pipeline"
      - if: ${{ github.event.pull_request.draft == false }}
        # uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        shell: bash
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        run: |
          echo "Triggering CircleCI pipeline for $GITHUB_HEAD_REF. $GITHUB_REF. $GITHUB_BASE_REF. $GITHUB_REF_NAME & $GITHUB_REPOSITORY & $GITHUB_REPOSITORY_OWNER"

          echo "${{ github.event.pull_request }}"

          response=$(curl -X POST https://circleci.com/api/v2/project/github/cypress-io/cypress/pipeline \
            --header "Circle-Token:$CIRCLE_TOKEN" \
            --header "content-type:application/json" \
            --data "{\"branch\":\"$GITHUB_HEAD_REF\"}" \
            --silent
          )

          echo "$response"

          if [ "$(jq 'has("message")' <<< $response )" == "true" ]; then
            echo "error triggering"
            exit 1;
          fi